In [1]:
import os
import pandas as pd
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler
from sklearn.impute import SimpleImputer as Imputer
from sklearn.base import BaseEstimator, TransformerMixin
import numpy as np

FILE_PATH = os.path.join("ashrae-energy-prediction", "datasets")

def load_csv_data(csvName, path=FILE_PATH):
    csv_path = os.path.join(path, csvName)
    return pd.read_csv(csv_path)


# load csv
building_metadata = load_csv_data("building_metadata.csv")

#train = load_csv_data("train.csv")
test = load_csv_data("test.csv")

#weather_train = load_csv_data("weather_train.csv")
weather_test = load_csv_data("weather_test.csv")

In [2]:
class DataFrameSelector(BaseEstimator, TransformerMixin):
    def __init__(self, attribute_names):
        self.attribute_names = attribute_names
    def fit(self, X, y=None):
        return self
    def transform(self, X):
        return X[self.attribute_names].values

In [3]:
class DataFrameImputer(TransformerMixin):

    def __init__(self):
        """Impute missing values.

        Columns of dtype object are imputed with the most frequent value 
        in column.

        Columns of other types are imputed with mean of column.

        """
    def fit(self, X, y=None):

        self.fill = pd.Series([X[c].value_counts().index[0]
            if X[c].dtype == np.dtype('O') else X[c].mean() for c in X],
            index=X.columns)

        return self

    def transform(self, X, y=None):
        return X.fillna(self.fill)

In [4]:
class DataAppender(TransformerMixin):
    def __init__(self, building, weather):
        self.building = building
        self.weather = weather

    def fit(self, X, y=None):
        return self
    def transform(self, X, y=None):

        train = X
        building_metadata = self.building
        weather_train = self.weather

        traim_tmp = pd.merge(train, building_metadata,
                       how="left", on = "building_id")

        train_all_join = pd.merge(traim_tmp.iloc[:,[0,1,2,3,4]], 
                                 weather_train, 
                                 how="left", on=["site_id", "timestamp"])

        month_day = train_all_join["timestamp"].str.replace('(.*)-(.*)-(.*) (.*)', r'\2\3', regex=True)
        month_day_enc = month_day.replace('^0(.*)', r'\1', regex=True)
        month_day_enc_int = month_day_enc.astype(int)
        train_all_join["month"] = month_day_enc_int
        
        print(train_all_join.columns)

        return np.array(train_all_join)

In [20]:
data_appender = DataAppender(building_metadata, weather_train)
train_all_np = data_appender.fit_transform(train)

NameError: name 'weather_train' is not defined

In [9]:
columns = ['building_id', 'meter', 'timestamp', 'site_id',
       'air_temperature', 'cloud_coverage', 'dew_temperature',
       'precip_depth_1_hr', 'sea_level_pressure', 'wind_direction',
       'wind_speed', 'month']

In [19]:
train_all = pd.DataFrame(train_all_np, columns=columns)

NameError: name 'train_all_np' is not defined

In [37]:
train_all.to_pickle('ashrae-energy-prediction/data/train_all_pkl.zip')

In [15]:
train_all = pd.read_pickle('ashrae-energy-prediction/data/train_all_pkl.zip')

In [16]:
from sklearn.impute import SimpleImputer

no_timestamp = train_all.drop(["timestamp"], axis=1)
num_attribs = list(no_timestamp)

num_pipeline = Pipeline(
    [
        ('selector', DataFrameSelector(num_attribs)),
        #('data_frame_imputer', DataFrameImputer()),
        ('simple_imputer', SimpleImputer(missing_values=np.nan, strategy='mean')),
        ('min_max_scaler', MinMaxScaler()),
    ]
)


train_noTimestamp_inputed = num_pipeline.fit_transform(no_timestamp)

train_noTimestamp_inputed_data_frame = pd.DataFrame(train_noTimestamp_inputed, columns=no_timestamp.columns)
train_noTimestamp_inputed_data_frame["timestamp"] = train_all["timestamp"]

train_prepared = train_noTimestamp_inputed_data_frame

In [17]:
train_prepared

,building_id,meter,meter_reading,site_id,air_temperature,cloud_coverage,dew_temperature,precip_depth_1_hr,sea_level_pressure,wind_direction,wind_speed,month,timestamp
0,0.000000,0.0,0.000000e+00,0.0,0.708279,0.666667,0.900164,0.005222,0.666235,0.0,0.000000,0.0,2016-01-01 00:00:00
1,0.000691,0.0,0.000000e+00,0.0,0.708279,0.666667,0.900164,0.005222,0.666235,0.0,0.000000,0.0,2016-01-01 00:00:00
2,0.001381,0.0,0.000000e+00,0.0,0.708279,0.666667,0.900164,0.005222,0.666235,0.0,0.000000,0.0,2016-01-01 00:00:00
3,0.002072,0.0,0.000000e+00,0.0,0.708279,0.666667,0.900164,0.005222,0.666235,0.0,0.000000,0.0,2016-01-01 00:00:00
4,0.002762,0.0,0.000000e+00,0.0,0.708279,0.666667,0.900164,0.005222,0.666235,0.0,0.000000,0.0,2016-01-01 00:00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...
20216095,0.997238,0.0,3.994577e-07,1.0,0.402102,0.211158,0.481178,0.000000,0.521345,0.5,0.463158,1.0,2016-12-31 23:00:00
20216096,0.997928,0.0,2.202724e-07,1.0,0.402102,0.211158,0.481178,0.000000,0.521345,0.5,0.463158,1.0,2016-12-31 23:00:00
20216097,0.998619,0.0,0.000000e+00,1.0,0.402102,0.211158,0.481178,0.000000,0.521345,0.5,0.463158,1.0,2016-12-31 23:00:00
20216098,0.999309,0.0,7.284966e-06,1.0,0.402102,0.211158,0.481178,0.000000,0.521345,0.5,0.463158,1.0,2016-12-31 23:00:00
20216099,1.000000,0.0,1.301091e-07,1.0,0.402102,0.211158,0.481178,0.000000,0.521345,0.5,0.463158,1.0,2016-12-31 23:00:00

In [18]:
train_prepared.to_pickle('ashrae-energy-prediction/data/train_prepared_pkl.zip')

In [5]:
##### for test
data_appender = DataAppender(building_metadata, weather_test)
test_all_np = data_appender.fit_transform(test)

Index(['row_id', 'building_id', 'meter', 'timestamp', 'site_id',
       'air_temperature', 'cloud_coverage', 'dew_temperature',
       'precip_depth_1_hr', 'sea_level_pressure', 'wind_direction',
       'wind_speed', 'month'],
      dtype='object')

In [6]:
test_columns = ['row_id', 'building_id', 'meter', 'timestamp', 'site_id',
       'air_temperature', 'cloud_coverage', 'dew_temperature',
       'precip_depth_1_hr', 'sea_level_pressure', 'wind_direction',
       'wind_speed', 'month']

In [7]:
import pandas as pd
test_all = pd.DataFrame(test_all_np, columns=test_columns)

In [9]:
test_all.to_pickle('ashrae-energy-prediction/tmpdata/test_all_pkl.zip')

In [10]:
test_all.head(10)

,row_id,building_id,meter,timestamp,site_id,air_temperature,cloud_coverage,dew_temperature,precip_depth_1_hr,sea_level_pressure,wind_direction,wind_speed,month
0,0,0,0,2017-01-01 00:00:00,0,17.8,4,11.7,NaN,1021.4,100,3.6,101
1,1,1,0,2017-01-01 00:00:00,0,17.8,4,11.7,NaN,1021.4,100,3.6,101
2,2,2,0,2017-01-01 00:00:00,0,17.8,4,11.7,NaN,1021.4,100,3.6,101
3,3,3,0,2017-01-01 00:00:00,0,17.8,4,11.7,NaN,1021.4,100,3.6,101
4,4,4,0,2017-01-01 00:00:00,0,17.8,4,11.7,NaN,1021.4,100,3.6,101
5,5,5,0,2017-01-01 00:00:00,0,17.8,4,11.7,NaN,1021.4,100,3.6,101
6,6,6,0,2017-01-01 00:00:00,0,17.8,4,11.7,NaN,1021.4,100,3.6,101
7,7,7,0,2017-01-01 00:00:00,0,17.8,4,11.7,NaN,1021.4,100,3.6,101
8,8,7,1,2017-01-01 00:00:00,0,17.8,4,11.7,NaN,1021.4,100,3.6,101
9,9,8,0,2017-01-01 00:00:00,0,17.8,4,11.7,NaN,1021.4,100,3.6,101

In [12]:
from sklearn.impute import SimpleImputer

def to_prepared(tmp):

    tmp['timestamp'] = pd.to_datetime(tmp['timestamp'])
    tmp['timestamp'] = tmp['timestamp'].view('int64')

    num_attribs = list(tmp)

    num_pipeline = Pipeline(
        [
            ('selector', DataFrameSelector(num_attribs)),
            #('data_frame_imputer', DataFrameImputer()),
            ('simple_imputer', SimpleImputer(missing_values=np.nan, strategy='mean')),
            ('min_max_scaler', MinMaxScaler()),
        ]
    )


    inputed = num_pipeline.fit_transform(tmp)

    inputed_data_frame = pd.DataFrame(inputed, columns=tmp.columns)

    return inputed_data_frame

In [13]:
test_prepared = to_prepared(test_all)

In [14]:
test_prepared

,row_id,building_id,meter,timestamp,site_id,air_temperature,cloud_coverage,dew_temperature,precip_depth_1_hr,sea_level_pressure,wind_direction,wind_speed,month
0,0.000000e+00,0.000000,0.0,0.000000,0.0,0.600785,0.444444,0.742710,0.003208,0.632522,0.277778,0.148760,0.000000
1,2.398220e-08,0.000691,0.0,0.000000,0.0,0.600785,0.444444,0.742710,0.003208,0.632522,0.277778,0.148760,0.000000
2,4.796439e-08,0.001381,0.0,0.000000,0.0,0.600785,0.444444,0.742710,0.003208,0.632522,0.277778,0.148760,0.000000
3,7.194659e-08,0.002072,0.0,0.000000,0.0,0.600785,0.444444,0.742710,0.003208,0.632522,0.277778,0.148760,0.000000
4,9.592878e-08,0.002762,0.0,0.000000,0.0,0.600785,0.444444,0.742710,0.003208,0.632522,0.277778,0.148760,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
41697595,9.999999e-01,0.997238,0.0,0.675781,1.0,0.570755,0.219261,0.672144,0.003208,0.565941,0.482891,0.139924,0.361062
41697596,9.999999e-01,0.997928,0.0,0.675781,1.0,0.570755,0.219261,0.672144,0.003208,0.565941,0.482891,0.139924,0.361062
41697597,1.000000e+00,0.998619,0.0,0.675781,1.0,0.570755,0.219261,0.672144,0.003208,0.565941,0.482891,0.139924,0.361062
41697598,1.000000e+00,0.999309,0.0,0.675781,1.0,0.570755,0.219261,0.672144,0.003208,0.565941,0.482891,0.139924,0.361062
41697599,1.000000e+00,1.000000,0.0,0.675781,1.0,0.570755,0.219261,0.672144,0.003208,0.565941,0.482891,0.139924,0.361062

In [15]:
test_prepared.to_pickle('ashrae-energy-prediction/tmpdata/test_prepared_pkl.zip')

In [18]:
train_prepared = pd.read_pickle('ashrae-energy-prediction/tmpdata/train_prepared_pkl.zip')
train_prepared

,building_id,meter,timestamp,meter_reading,site_id,air_temperature,cloud_coverage,dew_temperature,precip_depth_1_hr,sea_level_pressure,wind_direction,wind_speed,month
0,0.000000,0.0,0.0,0.000000e+00,0.0,0.708279,0.666667,0.900164,0.005222,0.666235,0.0,0.000000,0.0
1,0.000691,0.0,0.0,0.000000e+00,0.0,0.708279,0.666667,0.900164,0.005222,0.666235,0.0,0.000000,0.0
2,0.001381,0.0,0.0,0.000000e+00,0.0,0.708279,0.666667,0.900164,0.005222,0.666235,0.0,0.000000,0.0
3,0.002072,0.0,0.0,0.000000e+00,0.0,0.708279,0.666667,0.900164,0.005222,0.666235,0.0,0.000000,0.0
4,0.002762,0.0,0.0,0.000000e+00,0.0,0.708279,0.666667,0.900164,0.005222,0.666235,0.0,0.000000,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
20216095,0.997238,0.0,1.0,3.994577e-07,1.0,0.402102,0.211158,0.481178,0.000000,0.521345,0.5,0.463158,1.0
20216096,0.997928,0.0,1.0,2.202724e-07,1.0,0.402102,0.211158,0.481178,0.000000,0.521345,0.5,0.463158,1.0
20216097,0.998619,0.0,1.0,0.000000e+00,1.0,0.402102,0.211158,0.481178,0.000000,0.521345,0.5,0.463158,1.0
20216098,0.999309,0.0,1.0,7.284966e-06,1.0,0.402102,0.211158,0.481178,0.000000,0.521345,0.5,0.463158,1.0
20216099,1.000000,0.0,1.0,1.301091e-07,1.0,0.402102,0.211158,0.481178,0.000000,0.521345,0.5,0.463158,1.0

In [23]:

train_label = train_prepared["meter_reading"]
trains = train_prepared[["meter", "wind_speed", "sea_level_pressure", "air_temperature", "dew_temperature", "month"]]

### normal
from sklearn.ensemble import RandomForestRegressor
forest_reg = RandomForestRegressor()
forest_reg.fit(trains, train_label)

/Users/takahisahirota/Documents/repo/ml/env/lib/python3.7/site-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)

RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
                      max_features='auto', max_leaf_nodes=None,
                      min_impurity_decrease=0.0, min_impurity_split=None,
                      min_samples_leaf=1, min_samples_split=2,
                      min_weight_fraction_leaf=0.0, n_estimators=10,
                      n_jobs=None, oob_score=False, random_state=None,
                      verbose=0, warm_start=False)

In [ ]:
## gread search
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import GridSearchCV

param_grid = [
    {'n_estimators': [3, 9, 29], 'max_features': [2, 4, 6]},
    {'bootstrap': [False], 'n_estimators': [3, 9], 'max_features':[2,3,4]},
]

forest_reg = RandomForestRegressor()

grid_search = GridSearchCV(forest_reg, param_grid, cv=5,
                          scoring='neg_mean_squared_error')
grid_search.fit(trains, train_label)

forest_reg.fit(trains, train_label)

In [ ]:
forest_reg.best_params_

In [24]:
test_features = test_prepared[["meter", "wind_speed", "sea_level_pressure", "air_temperature", "dew_temperature", "month"]]
my_prediction = forest_reg.predict(test_features)

In [37]:
my_prediction.shape

(41697600,)

In [34]:
rounded_meter_reading = my_prediction.round(4)

ValueError: Shape of passed values is (41697600, 1), indices imply (41697600, 2)

In [44]:
my_solution = pd.DataFrame(rounded_meter_reading, columns = ["meter_reading"])

In [46]:
my_solution.describe()

       meter_reading
count   4.169760e+07
mean    8.455024e-05
std     7.119952e-04
min     0.000000e+00
25%     0.000000e+00
50%     0.000000e+00
75%     0.000000e+00
max     2.100000e-02

In [47]:
# to csv
my_solution.to_csv("ashrae-energy-prediction/results/my_solution.csv.gz", index_label = ["row_id"], compression='gzip')